# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUserNavigatesToAboutUs():
  def setup_method(self, method):
      self.driver = webdriver.Firefox()
      self.driver.maximize_window()
      self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_userNavigatesToAboutUs(self):
    self.driver.get("http://localhost:8000/")
    self.driver.maximize_window()
    wait = WebDriverWait(self.driver, 50)

    # Click to About Us
    about_us_link = wait.until(EC.element_to_be_clickable((By.LINK_TEXT, "ABOUT US")))
    self.driver.execute_script("arguments[0].scrollIntoView({block: 'center'});", about_us_link)
    time.sleep(2)
    self.driver.execute_script("arguments[0].click();", about_us_link)

    wait.until(EC.presence_of_element_located((By.TAG_NAME, "h1")))
    time.sleep(2)
    
    assert "About Us" in self.driver.title

    # Click [link] that goes to Google Form
    element = wait.until(EC.presence_of_element_located((By.LINK_TEXT, "[link]")))
    self.driver.execute_script("arguments[0].scrollIntoView({block: 'center'});", element)
    time.sleep(4)
    self.driver.execute_script("arguments[0].click();", element)
    time.sleep(4)

    # Click on clear form button
    wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, ".kCyAyd .NPEfkd"))).click()
    time.sleep(3)
    self.driver.close()