# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUpdatepasswordtoanewoneandchangeitback():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_updatepasswordtoanewoneandchangeitback(self):
    self.driver.get("http://localhost:8000/")
    self.driver.maximize_window()
    wait = WebDriverWait(self.driver, 50)

    # Wait for full page load
    wait.until(lambda driver: driver.execute_script('return document.readyState') == 'complete')


    # User Logins
    login = wait.until(EC.element_to_be_clickable((By.LINK_TEXT, "LOGIN")))
    self.driver.execute_script("arguments[0].scrollIntoView({block: 'center'});", login)
    login.click()
    time.sleep(2)

    wait.until(EC.presence_of_element_located((By.ID, "id_username")))
    self.driver.find_element(By.ID, "id_username").send_keys("admin")
    self.driver.find_element(By.ID, "id_password").send_keys("!password")
    self.driver.find_element(By.CSS_SELECTOR, ".me-3").click()
    time.sleep(2)

    self.driver.get("http://localhost:8000/account/")

    # User changes password to !password1
    clickpassword = wait.until(EC.element_to_be_clickable((By.ID, "passwordButton")))
    self.driver.execute_script("arguments[0].scrollIntoView({block: 'center'});", clickpassword)
    time.sleep(2)
    self.driver.execute_script("arguments[0].click();", clickpassword)
    time.sleep(2)

    self.driver.find_element(By.ID, "id_old_password").click()
    self.driver.find_element(By.ID, "id_old_password").send_keys("!password")
    time.sleep(2)
    self.driver.find_element(By.ID, "id_new_password1").send_keys("weak")
    time.sleep(2)

    # scroll down to password confirmation input field; weak password
    passwordconfirm = wait.until(EC.element_to_be_clickable((By.ID, "id_new_password2")))
    self.driver.execute_script("arguments[0].scrollIntoView({block: 'center'});", passwordconfirm)
    self.driver.find_element(By.ID, "id_new_password2").send_keys("weak")
    time.sleep(2)

    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(1)").click()
    time.sleep(3)

    # Wrong old password
    self.driver.find_element(By.ID, "id_old_password").click()
    self.driver.find_element(By.ID, "id_old_password").clear()
    self.driver.find_element(By.ID, "id_old_password").send_keys("weak")
    self.driver.find_element(By.ID, "id_new_password1").click()
    self.driver.find_element(By.ID, "id_new_password1").clear()
    self.driver.find_element(By.ID, "id_new_password1").send_keys("!password1")
    self.driver.find_element(By.ID, "id_new_password2").click()
    self.driver.find_element(By.ID, "id_new_password2").clear()
    self.driver.find_element(By.ID, "id_new_password2").send_keys("!password1")
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(1)").click()
    time.sleep(3)

    # Good password
    self.driver.find_element(By.ID, "id_old_password").click()
    self.driver.find_element(By.ID, "id_old_password").clear()
    self.driver.find_element(By.ID, "id_old_password").send_keys("!password")
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(1)").click()
    time.sleep(2)

    alert = self.driver.switch_to.alert
    assert alert.text == "Password updated successfully ✅"
    time.sleep(2)
    alert.accept()
    time.sleep(2)

    # User switches back to !password
    clickpassword1 = wait.until(EC.element_to_be_clickable((By.ID, "passwordButton")))
    self.driver.execute_script("arguments[0].scrollIntoView({block: 'center'});", clickpassword1)
    time.sleep(2)
    self.driver.execute_script("arguments[0].click();", clickpassword1)
    time.sleep(2)

    self.driver.find_element(By.ID, "id_old_password").click()
    self.driver.find_element(By.ID, "id_old_password").send_keys("!password1")
    time.sleep(2)
    self.driver.find_element(By.ID, "id_new_password1").send_keys("!password")
    time.sleep(2)

    # sroll down to password confirmation input field
    passwordconfirm1 = wait.until(EC.element_to_be_clickable((By.ID, "id_new_password2")))
    self.driver.execute_script("arguments[0].scrollIntoView({block: 'center'});", passwordconfirm1)
    self.driver.find_element(By.ID, "id_new_password2").send_keys("!password")
    time.sleep(2)

    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(1)").click()
    time.sleep(2)

    alert = self.driver.switch_to.alert
    assert alert.text == "Password updated successfully ✅"
    time.sleep(2)
    alert.accept()
    time.sleep(2)

    self.driver.close()