# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUserregistersaccount():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_userregistersaccount(self):
    self.driver.get("http://localhost:8000/")
    self.driver.maximize_window()
    wait = WebDriverWait(self.driver, 50)

    # User clicks login on navbar
    time.sleep(2)
    self.driver.find_element(By.LINK_TEXT, "LOGIN").click()
    time.sleep(2)

    # Go to registration form
    self.driver.find_element(By.LINK_TEXT, "Register").click()
    time.sleep(2)
    self.driver.find_element(By.ID, "id_username").click()
    self.driver.find_element(By.ID, "id_username").send_keys("cheesestick")
    time.sleep(2)
    self.driver.find_element(By.ID, "id_password1").send_keys("flintandsteel")
    self.driver.find_element(By.ID, "id_password2").send_keys("flintandsteel")
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
    time.sleep(3)
    self.driver.close()