# Generated by Selenium IDE
import pytest
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.common.keys import Keys

class TestAuthenticatedUserMakesAnEvent():
    def setup_method(self, method):
        self.driver = webdriver.Firefox()
        self.driver.maximize_window()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_authenticatedUserMakesAnEvent(self):
        self.driver.get("http://localhost:8000/restaurants/3/")
        self.driver.maximize_window()
        wait = WebDriverWait(self.driver, 20)

        # Wait for full page load
        wait.until(lambda driver: driver.execute_script('return document.readyState') == 'complete')

        # User Logins
        login = wait.until(EC.element_to_be_clickable((By.LINK_TEXT, "LOGIN")))
        self.driver.execute_script("arguments[0].scrollIntoView({block: 'center'});", login)
        login.click()
        time.sleep(2)

        wait.until(EC.presence_of_element_located((By.ID, "id_username")))
        self.driver.find_element(By.ID, "id_username").send_keys("admin")
        self.driver.find_element(By.ID, "id_password").send_keys("!password")
        self.driver.find_element(By.CSS_SELECTOR, ".me-3").click()
        time.sleep(2)

        # Add Event
        add_event_btn = wait.until(EC.element_to_be_clickable((By.LINK_TEXT, "Add Event")))
        self.driver.execute_script("arguments[0].scrollIntoView({block: 'center'});", add_event_btn)
        time.sleep(2)
        self.driver.execute_script("arguments[0].click();", add_event_btn)

        # Event form interaction
        wait.until(EC.presence_of_element_located((By.ID, "id_name")))
        self.driver.find_element(By.ID, "id_name").send_keys("Sushi Time")
        time.sleep(2)

        # Start time
        self.driver.find_element(By.ID, "start-time-picker-icon").click()
        wait.until(EC.element_to_be_clickable((By.LINK_TEXT, "30"))).click()
        self.driver.find_element(By.CSS_SELECTOR, ".ui-datepicker-close").click()
        time.sleep(2)

        # End time
        self.driver.find_element(By.ID, "id_end_time").click()
        wait.until(EC.element_to_be_clickable((By.LINK_TEXT, "30"))).click()
        self.driver.find_element(By.CSS_SELECTOR, ".ui-datepicker-close").click()
        time.sleep(2)

        # Description
        self.driver.find_element(By.ID, "id_description").send_keys("I love sushi.")
        time.sleep(2)

        # Submit the form
        self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(1)").click()
        time.sleep(3)

        # User views event
        self.driver.find_element(By.LINK_TEXT, "Sushi Time").click()
        time.sleep(2)
        self.driver.find_element(By.CSS_SELECTOR, ".justify-content-center > .btn").click()
        time.sleep(2)

        # User views all events
        self.driver.find_element(By.LINK_TEXT, "ALL EVENTS").click()
        time.sleep(3)
        self.driver.find_element(By.CSS_SELECTOR, ".col-md-15:nth-child(2) a").click()
        time.sleep(2)

        # User makes another event
        self.driver.find_element(By.LINK_TEXT, "NEW EVENT").click()
        time.sleep(2)
        self.driver.find_element(By.ID, "id_name").click()
        time.sleep(2)
        self.driver.find_element(By.ID, "id_name").send_keys("Cheese")
        time.sleep(2)
        self.driver.find_element(By.ID, "id_start_time").click()
        time.sleep(2)
        self.driver.find_element(By.LINK_TEXT, "30").click()
        time.sleep(2)
        self.driver.find_element(By.ID, "id_end_time").click()
        time.sleep(2)
        self.driver.find_element(By.LINK_TEXT, "30").click()
        time.sleep(2)
        dropdown = self.driver.find_element(By.ID, "id_location_object")
        time.sleep(2)
        dropdown.find_element(By.XPATH, "//option[. = 'El Museo Latino']").click()
        time.sleep(2)
        self.driver.find_element(By.CSS_SELECTOR, "#id_location_object > option:nth-child(11)").click()
        self.driver.find_element(By.ID, "id_description").click()
        self.driver.find_element(By.ID, "id_description").send_keys("I hate cheese sticks.")
        time.sleep(2)
        self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(1)").click()
        time.sleep(3)

        self.driver.close()