# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestChangeProfilePicture():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_changeProfilePicture(self):
    self.driver.get("http://localhost:8000/")
    self.driver.maximize_window()
    wait = WebDriverWait(self.driver, 50)

    # Wait for full page load
    wait.until(lambda driver: driver.execute_script('return document.readyState') == 'complete')


    # User Logins
    login = wait.until(EC.element_to_be_clickable((By.LINK_TEXT, "LOGIN")))
    self.driver.execute_script("arguments[0].scrollIntoView({block: 'center'});", login)
    login.click()
    time.sleep(2)

    wait.until(EC.presence_of_element_located((By.ID, "id_username")))
    self.driver.find_element(By.ID, "id_username").send_keys("admin")
    self.driver.find_element(By.ID, "id_password").send_keys("!password")
    self.driver.find_element(By.CSS_SELECTOR, ".me-3").click()
    time.sleep(2)

    # User changes profile picture
    self.driver.get("http://localhost:8000/account/")
    time.sleep(2)
    self.driver.find_element(By.ID, "choosePictureBtn").click()
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".selectable-picture:nth-child(1)").click()
    time.sleep(2)
    self.driver.find_element(By.ID, "choosePictureBtn").click()
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".selectable-picture:nth-child(6)").click()
    time.sleep(3)

    self.driver.close()