# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestPlaces():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_places(self):
    self.driver.get("http://localhost:8000/places/home/")
    self.driver.set_window_size(1284, 864)
    time.sleep(2)
    self.driver.find_element(By.ID, "right-arrow").click()
    time.sleep(2)
    self.driver.find_element(By.ID, "right-arrow").click()
    time.sleep(2)
    element = self.driver.find_element(By.ID, "right-arrow")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".categories-card:nth-child(4)").click()
    time.sleep(2)
    self.driver.find_element(By.LINK_TEXT, "Mosque").click()
    time.sleep(2)
    self.driver.find_element(By.LINK_TEXT, "Lodging").click()
    time.sleep(2)
    view_detail = self.driver.find_element(By.XPATH, "//a[contains(text(), 'View Detail') and contains(@href, '/places/188/')]")
    self.driver.execute_script("arguments[0].click();", view_detail)
    time.sleep(2)
    back_to_all_places = self.driver.find_element(By.XPATH, "//a[contains(text(), 'Back to All Places') and @href='/places/all/?category=']")
    self.driver.execute_script("arguments[0].click();", back_to_all_places)
    time.sleep(2)
    self.driver.close()
  
