# Generated by Django 5.1.6 on 2025-03-25 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the place', max_length=100, verbose_name='Place Name')),
                ('address', models.CharField(help_text='Place address', max_length=100, verbose_name='Address')),
                ('phone', models.CharField(help_text='Phone number', max_length=20, verbose_name='Phone')),
                ('website', models.URLField(help_text='Website URL', verbose_name='Website')),
                ('category', models.CharField(help_text='Category of the place', max_length=50, verbose_name='Category')),
                ('price_level', models.CharField(blank=True, help_text='Price level of the restaurant', max_length=50, null=True, verbose_name='Price Level')),
                ('rating', models.DecimalField(blank=True, decimal_places=1, help_text='Rating of the restaurant', max_digits=2, null=True, verbose_name='Rating')),
                ('description', models.TextField(help_text='Place description', verbose_name='Description')),
                ('image', models.ImageField(help_text='Image of the place', upload_to='images/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Place',
                'verbose_name_plural': 'Places',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the restaurant', max_length=100, verbose_name='Restaurant Name')),
                ('address', models.CharField(help_text='Restaurant address', max_length=100, verbose_name='Address')),
                ('phone', models.CharField(help_text='Phone number', max_length=20, verbose_name='Phone')),
                ('website', models.URLField(help_text='Website URL', verbose_name='Website')),
                ('category', models.CharField(help_text='Category of the restaurant', max_length=50, verbose_name='Category')),
                ('price_level', models.CharField(blank=True, help_text='Price level of the restaurant', max_length=50, null=True, verbose_name='Price Level')),
                ('rating', models.DecimalField(blank=True, decimal_places=1, help_text='Rating of the restaurant', max_digits=2, null=True, verbose_name='Rating')),
                ('description', models.TextField(help_text='Restaurant description', verbose_name='Description')),
                ('image', models.ImageField(help_text='Image of the restaurant', upload_to='images/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Restaurant',
                'verbose_name_plural': 'Restaurants',
            },
        ),
    ]
