# Generated by Django 5.2 on 2025-04-26 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the place', max_length=100, verbose_name='Place Name')),
                ('address', models.CharField(help_text='Place address', max_length=100, verbose_name='Address')),
                ('phone', models.CharField(help_text='Phone number', max_length=20, verbose_name='Phone')),
                ('website', models.URLField(help_text='Website URL', verbose_name='Website')),
                ('category', models.CharField(help_text='Category of the place', max_length=50, verbose_name='Category')),
                ('predefined_category', models.CharField(blank=True, help_text='place category', max_length=50, null=True, verbose_name='Predefined Category')),
                ('price_level', models.CharField(blank=True, help_text='Price level of the restaurant', max_length=50, null=True, verbose_name='Price Level')),
                ('rating', models.DecimalField(blank=True, decimal_places=1, help_text='Rating of the restaurant', max_digits=2, null=True, verbose_name='Rating')),
                ('description', models.TextField(help_text='Place description', verbose_name='Description')),
                ('image', models.ImageField(help_text='Image of the place', upload_to='images/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Place',
                'verbose_name_plural': 'Places',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the restaurant', max_length=100, verbose_name='Restaurant Name')),
                ('address', models.CharField(help_text='Restaurant address', max_length=100, verbose_name='Address')),
                ('phone', models.CharField(help_text='Phone number', max_length=20, verbose_name='Phone')),
                ('website', models.URLField(help_text='Website URL', verbose_name='Website')),
                ('category', models.CharField(help_text='Category of the restaurant', max_length=50, verbose_name='Category')),
                ('predefined_category', models.CharField(blank=True, help_text='restaurant category', max_length=50, null=True, verbose_name='Predefined Category')),
                ('price_level', models.CharField(blank=True, help_text='Price level of the restaurant', max_length=50, null=True, verbose_name='Price Level')),
                ('rating', models.DecimalField(blank=True, decimal_places=1, help_text='Rating of the restaurant', max_digits=2, null=True, verbose_name='Rating')),
                ('description', models.TextField(help_text='Restaurant description', verbose_name='Description')),
                ('image', models.ImageField(help_text='Image of the restaurant', upload_to='images/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Restaurant',
                'verbose_name_plural': 'Restaurants',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Event Name')),
                ('start_time', models.DateTimeField(verbose_name='Start Time')),
                ('end_time', models.DateTimeField(verbose_name='End Time')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ('place', 'restaurant')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event Scheduling',
                'verbose_name_plural': 'Event Scheduling',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.CharField(blank=True, choices=[('profile_pictures/profile1.png', 'Profile 1'), ('profile_pictures/profile2.png', 'Profile 2'), ('profile_pictures/profile3.png', 'Profile 3'), ('profile_pictures/profile4.png', 'Profile 4'), ('profile_pictures/profile5.png', 'Profile 5'), ('profile_pictures/profile6.png', 'Profile 6'), ('profile_pictures/profile7.png', 'Profile 7'), ('profile_pictures/profile8.png', 'Profile 8'), ('profile_pictures/profile9.png', 'Profile 9'), ('profile_pictures/profile10.png', 'Profile 10'), ('profile_pictures/profile11.png', 'Profile 11'), ('profile_pictures/profile12.png', 'Profile 12'), ('profile_pictures/profile13.png', 'Profile 13'), ('profile_pictures/profile14.png', 'Profile 14'), ('profile_pictures/profile15.png', 'Profile 15'), ('profile_pictures/profile16.png', 'Profile 16')], help_text='Choose a preset profile picture', max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='omaha_places_app.place')),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='omaha_places_app.restaurant')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='SavedLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location_type', models.CharField(choices=[('place', 'Place'), ('restaurant', 'Restaurant')], max_length=20)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
