# Generated by Django 5.2 on 2025-04-26 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omaha_places_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savedlocation',
            options={'verbose_name': 'Saved Location', 'verbose_name_plural': 'Saved Locations'},
        ),
    ]
