# Generated by Django 5.1.6 on 2025-04-01 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("omaha_places_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="predefined_category",
            field=models.CharField(
                blank=True,
                help_text="place category",
                max_length=50,
                null=True,
                verbose_name="Predefined Category",
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="predefined_category",
            field=models.CharField(
                blank=True,
                help_text="restaurant category",
                max_length=50,
                null=True,
                verbose_name="Predefined Category",
            ),
        ),
    ]
