# Generated by Django 5.1.6 on 2025-04-08 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omaha_places_app', '0004_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
