# Generated by Django 5.2 on 2025-04-26 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omaha_places_app', '0008_savedlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedlocation',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
