# Generated by Django 5.2 on 2025-04-26 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omaha_places_app', '0009_alter_savedlocation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedlocation',
            name='location_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='savedlocation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
